charmabode-fe/authentication/auth_system/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

app_name = 'authentication_app'

urlpatterns = [
    path('', views.start, name = 'start-page'),
    path('home/', views.home, name = 'home'),
    path('auth/', views.auth, name = 'auth'),
    # path('logout_user', views.logout_user,name = 'logout'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('contact/', views.contact, name='contact'),
    path('design/', views.design, name='design'),
    path('room/', views.room, name='room'),

] 
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

charmabode-fe/authentication/authentication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_system.urls')),
]

charmabode-fe/authentication/auth_system/models.py
from django.db import models

# Create your models here.

charmabode-fe/authentication/auth_system/forms.py
# # authentication_app/forms.py
# from django import forms

# class LoginForm(forms.Form):
#     username = forms.CharField(min_length=4, widget=forms.TextInput(attrs={'class': 'input-field'}))
#     password = forms.CharField(min_length=4, widget=forms.PasswordInput(attrs={'class': 'input-field'}))

# class SignupForm(forms.Form):
#     username = forms.CharField(min_length=4, widget=forms.TextInput(attrs={'class': 'input-field'}))
#     email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'input-field'}))
#     password = forms.CharField(min_length=4, widget=forms.PasswordInput(attrs={'class': 'input-field'}))

charmabode-fe/authentication/auth_system/views.py
# from django.shortcuts import render, redirect
# from django.contrib.auth.models import User
# from django.contrib.auth import authenticate, login, logout
# from django.http import HttpResponse
# from django.contrib.auth.decorators import login_required
# from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# from .forms import LoginForm, SignupForm


# # Create your views here.
# @login_required
# def HomePage(request):
#     return render(request, 'auth_system/index.html', {})

# # def Register(request):
# #      if request.method == 'POST':
# #         fname = request.POST.get('fname')
# #         lname = request.POST.get('sname')
# #         name = request.POST.get('uname')
# #         email = request.POST.get('email')
# #         password = request.POST.get('pass')

# #         new_user = User.objects.create_user(name, email, password)
# #         new_user.first_name = fname
# #         new_user.last_name = lname

# #         new_user.save()
# #         return redirect('login-page')
     
# #      return render(request, 'auth_system/register.html', {})

# # def Login(request):
# #     if request.method == 'POST':
# #         name = request.POST.get('uname')
# #         password = request.POST.get('pass')

# #         user = authenticate(request, username=name, password=password) 
# #         if user is not None:
# #             login(request, user)
# #             return redirect('home-page')
# #         else:
# #             return HttpResponse('Error, user does not exist')


# #     return render(request, 'auth_system/login.html', {})

# # def auth_view(request):
# #     if request.method == 'POST':
# #         if 'signup' in request.POST:
# #             form = UserCreationForm(request.POST)
# #             if form.is_valid():
# #                 user = form.save()
# #                 login(request, user)
# #         elif 'login' in request.POST:
# #             form = AuthenticationForm(data = request.POST)
# #             if form.is_valid():
# #                 user = form.get_user()
# #                 login(request, user)
# #                 return redirect('home-page')
# #     else:
# #         form_signup = UserCreationForm()
# #         form_login = AuthenticationForm()
# #     return render(request, 'auth_system/auth.html', {'form_signup': form_signup, 'form_login': form_login})


# # authentication_app/views.py

# def auth_view(request):
#     show_login_form = True  # You can determine this based on some condition
#     login_form = LoginForm()
#     signup_form = SignupForm()
    
#     context = {
#         'show_login_form': show_login_form,
#         'login_form': login_form,
#         'signup_form': signup_form,
#     }
    
#     return render(request, 'auth_system/auth.html', context)

# def login_view(request):
#     if request.method == 'POST':
#         # Process login form submission
#         pass
    
#     return render(request, 'auth_system/auth.html', {'show_login_form': True, 'login_form': login_form})

# def signup_view(request):
#     if request.method == 'POST':
#         # Process signup form submission
#         pass
    
#     return render(request, 'authentication_app/auth.html', {'show_login_form': False, 'signup_form': signup_form})



from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
#@login_required 
def contact(request):
    return render(request, 'auth_system/contact.html', {})

def design(request):
    return render(request, 'auth_system/design.html', {})

def room(request):
    return render(request, 'auth_system/room.html', {})

def start(request):
    return render(request, 'auth_system/index.html', {})

def home(request):
    return render(request, 'auth_system/home.html', {})

def auth(request):
    error_message = None
    if request.method == 'POST':
        form_type = request.POST.get('form_type')  
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        if form_type == 'signin':
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                #messages.success(request, 'Login successful. Welcome back {username}!')
                return render(request, 'auth_system/home.html', {})  # Redirect to your desired page after successful login
            else:
                error_message = "Invalid login credentials. Please try again."
                #messages.error(request, 'Invalid username or password. Please try again')
        
        elif form_type == 'signup':
            email = request.POST.get('email')
            password2 = request.POST.get('password2')
            if password == password2:
                if User.objects.filter(username=username).exists():
                    #messages.error(request, 'Username taken')
                    error_message = 'Username taken'
                    #return render(request, 'auth_system/auth.html')
                    #return redirect('auth')
                elif User.objects.filter(email=email).exists():
                    #messages.error(request, 'Email taken')
                    error_message = 'Email taken'
                    #return render(request, 'auth_system/auth.html')
                    #return redirect('auth')
                else:
                    user = User.objects.create_user(username, email, password)
                    user.save()
                    # You might want to log the user in automatically after registration
                    #login(request, user)
                    return render(request, 'auth_system/auth.html', {})  # Redirect to your desired page after successful signup
            else:
                #messages.error("An error occurred during registration. Please try again.")
                error_message = "Passwords do not match"
                #return redirect('auth')
        
    #else:
        #error_message = None  # To handle initial rendering without error message
    
    context = {
        'error_message': error_message,
    }
    
    return render(request, 'auth_system/auth.html', context)


# def logout_user(request):
#     logout(request)
#     return render(request, 'auth_system/auth.html', {})




# from django.shortcuts import render, redirect
# from django.contrib.auth import authenticate, login
# from django.contrib.auth.models import User
# from django.contrib.auth.decorators import login_required
# from django.contrib import messages
# @login_required 

# def start(request):
#     return render(request, 'auth_system/index.html', {})

# def HomePage(request):
#      return render(request, 'auth_system/home.html', {})

# def auth(request):
#     if request.method == 'POST':
#         form_type = request.POST.get('form_type')  # This will be 'signin' or 'signup'
#         username = request.POST.get('username')
#         password = request.POST.get('password')
        
#         if form_type == 'signin':
#             user = authenticate(request, username=username, password=password)
#             if user is not None:
#                 login(request, user)
#             #    messages.success(request, 'Login successful. Welcome back {username}!')
#                 return redirect('home-page')  # Redirect to your desired page after successful login
#             else:
#                 # Handle incorrect login credentials
#                 error_message = "Invalid login credentials. Please try again."
#             #    messages.error(request, 'Invalid username or password.')
        
#         elif form_type == 'signup':
#             email = request.POST.get('email')
#             password2 = request.POST.get('password2')
#             if password == password2:
#                 if User.objects.filter(username=username).exists():
#                     messages.info(request, 'Username taken')
#                     return render(request, 'auth_system/auth.html')
#                 elif User.objects.filter(email=email).exists():
#                     messages.info(request, 'Email taken')
#                     return render(request, 'auth_system/auth.html')
#                 else:
#                     user = User.objects.create_user(username, email, password, password2)
#                     user.save()
#                     # You might want to log the user in automatically after registration
#                     # login(request, user)
#                     return redirect('home-page')  # Redirect to your desired page after successful signup
#             else:
#                 error_message = "An error occurred during registration. Please try again."
#                 return redirect('auth')
        
#     else:
#         error_message = None  # To handle initial rendering without error message
    
#     context = {
#         'error_message': error_message,
#     }
    
#     return render(request, 'auth_system/auth.html', context)

charmabode-fe/authentication/auth_system/templates/auth_system/auth.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sign in & Sign up Form</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <header>
      <input type ="checkbox" name ="" id ="chk1">
      <div class="logo"><h1>CharmAbode</h1></div>
      <!-- <div class="search-box">
        <form>
          <input type ="text" name ="search" id ="srch" placeholder="Search">
          <button type ="submit"><i class="fa fa-search"></i></button>
        </form>
      </div> -->
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">Design</a></li>
        <li><a href="#">About us</a></li>
        <li><a href="/contact/">Contact</a></li>
        <li>
          <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-instagram"></i></a>

        </li>
      </ul>
    <div class="menu">
  <label for="chk1">
    <i class="fa fa-bars"></i>
  </label>
  </div>
  </header>
    <main>
      <div class="box">
        <div class="inner-box">
          <div class="forms-wrap">
            <!-- <form id = "login-form" action="{% url 'authentication_app:auth' %}" method = "post" autocomplete="off" class="sign-in-form"> -->
              <form id = "login-form"  method = "post" autocomplete="off" class="sign-in-form">
              {% csrf_token %}
              <input type="hidden" name="form_type" value="signin">
              <div class="logo">
                <h4>CharmAbode</h4>
              </div>

              <div class="heading">
                <h2>Welcome Back</h2>
                <h6>Not registred yet?</h6>
                <a href="#" class="toggle">Sign up</a>
              </div>
              
                <div class="actual-form">
                  <div class="input-wrap">
                    <input 
                       type="text"
                       name = "username"
                      minlength="4"
                      class="input-field"
                      autocomplete="off"
                      required
                    /> 
                    <label>Username</label>
                  </div>
  
                  <div class="input-wrap">
                    <input
                      type="password"
                      name = "password"
                      minlength="4"
                      class="input-field"
                      autocomplete="off"
                      required
                    />
                    <label>Password</label>
                  </div>
  
                  <input type="submit" value="Sign In" class="sign-btn" />
  
                  <p class="text">
                    Forgot password ?
                    <a href="#">Get help</a> signing in
                  </p>
                </div>
              </form>
  
                <!--  <div class="actual-form">
                  {{ login_form.username.label_tag }}
                {{ login_form.username }}
                {{ login_form.password.label_tag }}
                {{ login_form.password }}
                <input type="submit" value="Sign In" class="sign-btn" />
                <p class="text">
                    Forgot password ? <a href="#">Get help</a> signing in
                </p>
            </div>
        </form> -->

            <form id = "signup-form" action="{% url 'authentication_app:auth' %}" method = "post" autocomplete="off" class="sign-up-form">
              {% csrf_token %}
              <input type="hidden" name="form_type" value="signup">
              <div class="logo">
                <h4>CharmAbode</h4>
              </div>

              <div class="heading">
                <h2>Get Started</h2>
                <h6>Already have an account?</h6>
                <a href="#" class="toggle">Sign in</a>
              </div>

              <div class="actual-form">
                <div class="input-wrap">
                  <input 
                    type="text"
                    name = "username"
                    minlength="4"
                    class="input-field"
                    autocomplete="off"
                    required
                    /> 
                  <label>Username</label>
                </div>

                <div class="input-wrap">
                  <input
                    type="email"
                    name = "email"
                    class="input-field"
                    autocomplete="off"
                    required
                  />
                  <label>Email</label>
                </div>

                <div class="input-wrap">
                  <input
                    type="password"
                    name = "password"
                    minlength="4"
                    class="input-field"
                    autocomplete="off"
                    required
                  />
                  <label>Password</label>
                </div>

                <div class="input-wrap">
                  <input
                    type="password"
                    name = "password2"
                    minlength="4"
                    class="input-field"
                    autocomplete="off"
                    required
                  />
                  <label>Confirm Password</label>
                </div>

                <input type="submit" value="Sign Up" class="sign-btn" />

                <p class="text">
                  By signing up, I agree to the
                  <a href="#">Terms of Services</a> and
                  <a href="#">Privacy Policy</a>
                </p>
              </div>
            </form>
          </div>
<!-- 
          <div id="toast-container" class="toast-container">
            <div id="toast" class="toast"></div>
        </div>
         -->
<!-- 
          {% if error_message %}
          <div class="error-message">
              {{ error_message }}
            </div>
          {% endif %} -->

          <div class="error-box ">
            {% if error_message %}
                {{ error_message }}
            {% endif %}
        </div>
        

          <!-- {% if error_message %}
    <script>
        showToast("{{ error_message }}", 50000); // Display for 5 seconds (5000 milliseconds)
    </script>
{% endif %} -->

<!-- 
              <div class="actual-form">
                    {{ signup_form.username.label_tag }}
                    {{ signup_form.username }}
                    {{ signup_form.email.label_tag }}
                    {{ signup_form.email }}
                    {{ signup_form.password.label_tag }}
                    {{ signup_form.password }}
                    <input type="submit" value="Sign Up" class="sign-btn" />
                    <p class="text">
                        By signing up, I agree to the <a href="#">Terms of Services</a> and <a href="#">Privacy Policy</a>
                    </p>
                </div>
            </form>
          </div> -->

          <div class="carousel">
            <div class="image-wrapper">
              <img src="{% static 'img/image1.jpeg' %}" class="image img-1 show" alt="" />
              <!-- <img src="./img/image2.jpeg" class="image img-2" alt="" /> -->
              <img src="{% static 'img/image3.jpeg' %}" class="image img-3" alt="" />
            </div> 
<!--     
            <div class="container">
              <div class="wrapper">
                  <img src="img/image1.jpeg">
                  <img src="img/image2.jpeg">
                  <img src="img/image3.jpeg">
      
              </div>
           -->

            <!-- <div class="text-slider">
                <div class="text-wrap">
                <div class="text-group">
                  <h2>Create your own courses</h2>
                  <h2>Customize as you like</h2>
                  <h2>Invite students to your class</h2>
                </div>
              </div>   -->

              <!-- <div class="bullets">
                <span class="active" data-value="1"></span>
                <span data-value="2"></span>
                <span data-value="3"></span>
              </div> -->
            <!-- </div> -->

            <div class="bullets">
              <span class="active" data-value="1"></span>
              <span data-value="2"></span>
              <span data-value="3"></span>
            </div>
          </div>
          </div>
        </div>
      </div> 
    </main>

    <!-- Javascript file -->

    <script type = "text/javascript" >
      const inputs = document.querySelectorAll(".input-field");
const toggle_btn = document.querySelectorAll(".toggle");
const main = document.querySelector("main");
const images = document.querySelectorAll(".image");

inputs.forEach((inp) => {
  inp.addEventListener("focus", () => {
    inp.classList.add("active");
  });
  inp.addEventListener("blur", () => {
    if (inp.value != "") return;
    inp.classList.remove("active");
  });
});

toggle_btn.forEach((btn) => {
  btn.addEventListener("click", () => {
    main.classList.toggle("sign-up-mode");

    // Toggle active image based on the current mode
    images.forEach((image) => {
      image.classList.toggle("show");
    });
  });
});
function showToast(message, duration) {
    const toastContainer = document.getElementById('toast-container');
    const toast = document.getElementById('toast');

    toast.textContent = message;
    toastContainer.style.display = 'block';

    setTimeout(function() {
        toastContainer.style.display = 'none';
    }, duration);
}

    </script> 
  </body>
</html>

charmabode-fe/authentication/auth_system/templates/auth_system/contact.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Contact Form</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/contact.css' %}" />
    <script
      src="https://kit.fontawesome.com/64d58efce2.js"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <header>
    <input type ="checkbox" name ="" id ="chk1">
    <div class="logo"><h1>CharmAbode</h1></div>
    <!-- <div class="search-box">
      <form>
        <input type ="text" name ="search" id ="srch" placeholder="Search">
        <button type ="submit"><i class="fa fa-search"></i></button>
      </form>
    </div> -->
    <ul>
      <li><a href="/home/">Home</a></li>
      <li><a href="/design/">Design</a></li>
      <li><a href="#">About us</a></li>
      <li><a href="/contact/">Contact</a></li>
      {% if user.is_authenticated %}
            <li style = "color: white">{{ user.username }}</li>
            <li><a href="/logout/">Logout</a></li> 
        {% endif %}
      <li>
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-instagram"></i></a>

      </li>
    </ul>
  <div class="menu">
<label for="chk1">
  <i class="fa fa-bars"></i>
</label>
</div>
</header>
    {% csrf_token %}
    <div class="container">
      <span class="big-circle"></span>
      <!-- <img src="img/shape.png" class="square" alt="" /> -->
      <div class="form">
        <div class="contact-info">
          <h3 class="title1">Let's get in touch</h3>
          <p class="text">
           We would love to respond to your queries.
           Feel free to get in touch with us.
          </p>

          <div class="info">
            <div class="information">
              <!-- <img src="location.png" class="icon" alt="" /> -->
              <p></p>
            </div> 
            <div class="information">
              <img src="{% static 'img/email.png' %}" class="icon" alt="" />
              <p>charmabodewe@gmail.com</p>
            </div>
            <div class="information">
              <img src="{% static 'img/phone.jpg' %}" class="icon" alt="" />
              <p>1234567890</p>
            </div>
          </div>

          <div class="social-media">
            <p>Connect with us :</p>
            <div class="social-icons">
              <a href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#">
                <i class="fab fa-instagram"></i>
              </a>
              <a href="#">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </div>
          </div>
        </div>

        <div class="contact-form">
          <!-- <span class="circle one"></span>
          <span class="circle two"></span> -->

          <form action="contact.html" autocomplete="off">
            <h3 class="title">Contact us</h3>
            <div class="input-container">
              <input type="text" name="name" class="input" />
              <label for="">Username</label>
              <span>Username</span>
            </div>
            <div class="input-container">
              <input type="email" name="email" class="input" />
              <label for="">Email</label>
              <span>Email</span>
            </div>
            <div class="input-container">
              <input type="tel" name="phone" class="input" />
              <label for="">Phone</label>
              <span>Phone</span>
            </div>
            <div class="input-container textarea">
              <textarea name="message" class="input"></textarea>
              <label for="">Feedback</label>
              <span>Message</span>
            </div>
            <input type="submit" value="Send" class="btn" />
          </form>
        </div>
      </div>
    </div>

    <script src="{% static 'js/app.js' %}"></script>
    <script src="https://smtpjs.com/v3/smtp.js"></script>
    <script>
      function sendEmail(){
        Email.send({
        Host : "smtp.elasticemail.com",
        Username :"charmabodewe@gmail.com",
        Password : "CB1FF96D93F3A628CF012356BEF249113CE7",
        //Username : "ragini.metlapalli@gmail.com",
        //Password : "D6134FD82C6852EB2B1D5EF0EB53787E0A31", //charm
        //Password : "DE95160A7AC392667909730F3A9AD3DF95AA", //ragini
        To : 'charmabodewe@gmail.com',
        From : "seemab857@gmail.com",
        Subject : "new contact form",
        Body : "And this is the body"
    }).then(
        message => alert(message)
    );
      }
    </script>
  </body>
</html>

charmabode-fe/authentication/auth_system/templates/auth_system/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  <link rel="stylesheet" href="{% static 'css/style-home.css' %}" />
  </head>
  <body>
    <!-- {% csrf_token %}  -->
    <header>
      <input type ="checkbox" name ="" id ="chk1">
      <div class="logo"><h1>CharmAbode</h1></div>
      <ul>
        <li><a href="/home/">Home</a></li>
        <li><a href="/design/">Design</a></li>
        <li><a href="#">About us</a></li>
        <li><a href="/contact/">Contact</a></li>
        {% if user.is_authenticated %}
            <li style = "color: white">{{ user.username }}</li>
            <li><a href="/logout/">Logout</a></li> 
        {% endif %}
        <li>
          <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-instagram"></i></a> 

        </li>
      </ul>
    <div class="menu">
  <label for="chk1">
    <i class="fa fa-bars"></i>
  </label>
  </div>
  </header>
  <main>
    <section class="create-design">
      <h2>Create a new design</h2>
      <div class="create-box" id = "plus" onclick = "goToDesignPage()">

          <span class="plus-icon">+</span>
          <!-- Create a new design -->
        </div>
    </section>
    <section class="previous-designs-container">
        <section class="previous-designs">
      <h2>Designs</h2>
      <div class="design-slider">
        <div class="design-box-container">
          <div class="design-box">
            <img src="{% static 'img/iso1.png' %}" alt="Design 1">
          </div>
          <div class="design-box">
            <img src="{% static 'img/iso2.png' %}" alt="Design 2">
          </div>
          <div class="design-box">
            <img src="{% static 'img/iso3.png' %}" alt="Design 3">
          </div>
          <div class="design-box">
            <img src="{% static 'img/iso4.jpg' %}" alt="Design 4">
          </div>
          <div class="design-box">
            <img src="{% static 'img/iso5.jpg' %}" alt="Design 5">
          </div>
          <div class="design-box">
            <img src="{% static 'img/iso6.jpg' %}" alt="Design 6">
          </div>
          <div class="design-box">
            <img src="{% static 'img/iso7.jpeg' %}" alt="Design 7">
          </div>
          <div class="design-box">
            <img src="{% static 'img/iso1.png' %}" alt="Design 8">
          </div>
          <div class="design-box">
            <img src="{% static 'img/iso2.png' %}" alt="Design 9">
          </div>
          <div class="design-box">
            <img src="{% static 'img/iso3.png' %}" alt="Design 10">
          </div> 
          <!-- Add more design boxes here -->
        </div>
        </div>
        <div class="slider-buttons">
        <button class="prev-button" onclick="slideDesigns(-1)">Prev</button>
        <button class="next-button" onclick="slideDesigns(1)">Next</button>
      </div>
    </section>
</section>
  </main>
</body>
<script>
     document.getElementById("plus").addEventListener("click", function() {
            window.location.href = "/design/";
        });
</script>
<script src="{% static 'js/script.js' %}"></script>
</html>

charmabode-fe/authentication/auth_system/templates/auth_system/index.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta name = "viewport" content = "width = device-width, initial-scale = 1.0">
        <title></title>
        {% load static %}
        <link rel = "stylesheet" href="{% static 'css/style-index.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/global.css' %}" />
        <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Italianno"
    />
    <link
      rel="stylesheet" href = "https://fonts.googleapis.com/css?family=Lilita One">
    </head>
    <body>
        {% csrf_token %}
        <div class = "caption">
        From  empty  space  to  perfect  place: It’s  your  creation
        </div>
        <div class="big">
            <div class = "small-img">
                <img src = "{% static 'img/1.jpeg' %}">
            </div>
            <div class = "small-img">
                <img src = "{% static 'img/2.jpeg' %}">
            </div>
            <div class = "small-img">
                <img src = "{% static 'img/3.jpeg' %}">
            </div>
            <div class = "small-img">
                <img src = "{% static 'img/4.jpeg' %}">
            </div>
            <div class = "small-img">
                <img src = "{% static 'img/5.jpeg' %}">
            </div>
            <div class = "small-img">
                <img src = "{% static 'img/6.jpeg' %}">
            </div>
            <div class = "small-img">
                <img src = "{% static 'img/7.jpeg' %}">
            </div>
            <div class = "small-img">
                <img src = "{% static 'img/8.jpeg' %}">
            </div>
            <div class = "small-img">
                <img src = "{% static 'img/9.jpeg' %}">
            </div>
        </div>
       <button id="get-started-button">Get Started</button>

    <script>
        document.getElementById("get-started-button").addEventListener("click", function() {
            window.location.href = "/auth/";
        });
    </script>
    </body>
</html>